'use strict';
const PHASES=['IDLE','APPROACH','IDENTIFYING','ENTRY_AUTHORIZED','ENTERING','POSITIONING','READY_TO_WEIGH','WEIGHING','LOCAL_COMMITTED','EXIT_AUTHORIZED','EXITING','COMPLETE'];
const STEP_COPY={IDLE:'Deck clear; waiting for vehicle',APPROACH:'Vehicle detected at approach',IDENTIFYING:'RFID + plate identity acquisition',ENTRY_AUTHORIZED:'Identity and empty-deck proof accepted',ENTERING:'Entry barrier released; truck entering',POSITIONING:'Front/rear deck sensors evaluated',READY_TO_WEIGH:'Truck positioned and interlocks satisfied',WEIGHING:'Controller frames audited; stability evaluated',LOCAL_COMMITTED:'Ticket durably committed locally',EXIT_AUTHORIZED:'Exit release authorized after commit',EXITING:'Truck clearing weighbridge',COMPLETE:'Transaction complete; permissive outputs off'};
const POS={IDLE:1,APPROACH:7,IDENTIFYING:13,ENTRY_AUTHORIZED:18,ENTERING:29,POSITIONING:43,READY_TO_WEIGH:48,WEIGHING:50,LOCAL_COMMITTED:53,EXIT_AUTHORIZED:63,EXITING:79,COMPLETE:94,FAULT_LOCKOUT:50};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let live=true,lastLpr='',demoTimer=null;
let data={health:null,wf:null,scale:null,io:null,id:null,storage:null,weights:[],events:[]};
function fmtN(n){return new Intl.NumberFormat('en-US').format(Number(n||0))}
function short(s,n=8){s=String(s||'');return s?s.slice(0,n):'—'}
function stateIndex(s){const i=PHASES.indexOf(s);return i<0?0:i}
function buildSteps(){$('steps').innerHTML=PHASES.map(p=>`<div class="step" data-phase="${p}"><i class="node"></i><div><strong>${p.replaceAll('_',' ')}</strong><small>${STEP_COPY[p]}</small></div></div>`).join('')}
buildSteps();
async function getJSON(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${url} ${r.status}`);return r.json()}
async function pollFast(){if(!live)return;const res=await Promise.allSettled(['/healthz','/api/workflow','/api/scale/status','/api/io/status','/api/identity','/api/storage/status'].map(getJSON));['health','wf','scale','io','id','storage'].forEach((k,i)=>{if(res[i].status==='fulfilled')data[k]=res[i].value});render()}
async function pollSlow(){if(!live)return;const res=await Promise.allSettled([getJSON('/api/audit/weights?limit=120'),getJSON('/api/audit/events?limit=100'),getJSON('/api/audit/weights/verify'),getJSON('/api/audit/events/verify')]);if(res[0].status==='fulfilled')data.weights=res[0].value.records||[];if(res[1].status==='fulfilled')data.events=res[1].value.records||[];$('rawVerify').textContent=res[2].status==='fulfilled'&&res[2].value.verified?'VERIFIED':'—';$('eventVerify').textContent=res[3].status==='fulfilled'&&res[3].value.verified?'VERIFIED':'—';renderChart();renderTimeline();renderMetrics()}
function render(){const h=data.health||{},wf=data.wf||{},sc=data.scale||{},io=data.io||{},identity=data.id||{},st=data.storage||{};const state=wf.state||'IDLE',mode=wf.mode||wf.transaction?.mode||'NORMAL',tx=wf.transaction||{};
 $('healthDot').className='dot '+(h.status==='ok'?'ok':'bad');$('healthText').textContent=h.status==='ok'?'EDGE ONLINE':'EDGE OFFLINE';
 const station=tx.station_id||h.station_id||'EDGE-01';$('stationTop').textContent=station;$('stationScene').textContent=station;$('dbTop').textContent=st.integrity==='ok'?'OK':'—';$('syncTop').textContent=st.pending_sync??'—';$('shaMini').textContent=short(h.git_sha||'',10);
 $('stateBadge').textContent=state.replaceAll('_',' ');$('modeBadge').textContent=mode;$('modeBadge').className='modebadge '+(String(mode).includes('DEGRADED')?'degraded':state==='FAULT_LOCKOUT'?'lockout':'');$('txShort').textContent=tx.id?`TX ${short(tx.id,10)}`:'NO ACTIVE TX';
 document.querySelectorAll('.step').forEach(el=>{const p=el.dataset.phase,pi=stateIndex(p),si=stateIndex(state);el.classList.toggle('done',state!=='FAULT_LOCKOUT'&&pi<si);el.classList.toggle('active',p===state);el.classList.toggle('block',state==='FAULT_LOCKOUT'&&p==='WEIGHING')});
 const reading=sc.last_reading||tx.accepted_weight||{},weight=reading.weight_kg??0,stable=!!reading.stable||!!tx.accepted_weight;$('weight').textContent=`${fmtN(weight)} kg`;$('weight').className='weight '+(stable?'stable':'');$('weightState').textContent=sc.connected?(stable?'STABLE · AUDITED':'LIVE · UNSTABLE'):(tx.accepted_weight?'ACCEPTED TICKET WEIGHT':'WAITING FOR LIVE FRAME');$('scaleDeck').classList.toggle('active',state==='WEIGHING'||state==='READY_TO_WEIGH');
 const inp=io.last_input||{},ap=io.applied||{};$('sEntry').classList.toggle('on',!!inp.entry_present);$('sFront').classList.toggle('on',!!inp.front_present);$('sRear').classList.toggle('on',!!inp.rear_present);$('sExit').classList.toggle('on',!!inp.exit_present);$('entryBarrier').classList.toggle('open',!!inp.entry_barrier_open||!!ap.entry_barrier_open);$('exitBarrier').classList.toggle('open',!!inp.exit_barrier_open||!!ap.exit_barrier_open);$('entryLight').classList.toggle('go',!!ap.entry_green);$('exitLight').classList.toggle('go',!!ap.exit_green);
 const rfid=identity.rfid?.tag||tx.rfid||tx.rfid_tag||'',plate=identity.lpr?.plate||tx.plate||'';$('rfidText').textContent=rfid||'—';$('plateText').textContent=plate||'—';$('plateTruck').textContent=plate||'—';$('positionText').textContent=tx.position||'—';$('rfid').classList.toggle('scan',state==='IDENTIFYING'&&!rfid);if(plate&&plate!==lastLpr){$('camera').classList.remove('flash');void $('camera').offsetWidth;$('camera').classList.add('flash');lastLpr=plate}
 $('truck').style.setProperty('--truck-x',POS[state]??50);$('truck').classList.toggle('moving',['APPROACH','ENTERING','EXITING'].includes(state));
 $('sigScale').className='sig '+(sc.connected?'ok':sc.enabled===false?'':'bad');$('devScale').textContent=sc.connected?'CONNECTED · '+(stable?'STABLE':'STREAMING'):(sc.enabled===false?'DISABLED':'DISCONNECTED');$('sigIO').className='sig '+(io.connected?'ok':io.enabled===false?'':'bad');$('devIO').textContent=io.connected?'MODBUS CONNECTED':(io.enabled===false?'DISABLED':'DISCONNECTED');$('sigRFID').className='sig '+(rfid?'ok':'');$('devRFID').textContent=rfid||'WAITING';$('sigLPR').className='sig '+(plate?'ok':'');$('devLPR').textContent=plate||'WAITING';renderMetrics();
}
function renderMetrics(){const st=data.storage||{};$('tickets').textContent=st.tickets??0;$('pending').textContent=st.pending_sync??0;$('rawCount').textContent=data.weights.length;$('eventSeq').textContent=data.events.length?data.events[data.events.length-1].seq||0:0}
function renderChart(){const rec=data.weights||[];if(!rec.length){$('chartLine').setAttribute('d','');$('chartStable').setAttribute('d','');$('chartDot').setAttribute('cx','0');return}const vals=rec.map(r=>({w:Number(r.event?.weight_kg??0),stable:!!r.event?.stable}));const max=Math.max(1000,...vals.map(v=>Math.abs(v.w)))*1.08,min=Math.min(0,...vals.map(v=>v.w)),range=max-min||1;const pts=vals.map((v,i)=>({x:i/(Math.max(1,vals.length-1))*1000,y:108-((v.w-min)/range)*100}));$('chartLine').setAttribute('d',pts.map((p,i)=>(i?'L':'M')+p.x.toFixed(1)+' '+p.y.toFixed(1)).join(' '));let seg='',open=false;pts.forEach((p,i)=>{if(vals[i].stable){seg+=(open?' L':' M')+p.x.toFixed(1)+' '+p.y.toFixed(1);open=true}else open=false});$('chartStable').setAttribute('d',seg);const p=pts[pts.length-1];$('chartDot').setAttribute('cx',p.x);$('chartDot').setAttribute('cy',p.y);$('chartMeta').textContent=`${vals.length} audited frames · peak ${fmtN(Math.max(...vals.map(v=>v.w)))} kg`}
function renderTimeline(){const rows=(data.events||[]).slice(-35).reverse();if(!rows.length){$('timeline').innerHTML='<div class="empty">Waiting for operational audit events…</div>';return}$('timeline').innerHTML=rows.map(r=>{const e=r.event||{},k=e.kind||'EVENT',cl=k.includes('OUTPUT')?'cmd':k.includes('TICKET')?'ticket':k.includes('FAULT')?'fault':'';const detail=e.action||e.reason||e.new_state||e.device||'',tm=e.at_utc?new Date(e.at_utc).toLocaleTimeString([],{hour12:false}):'';return `<div class="event ${cl}"><b>#${r.seq||'?'} ${esc(k)}</b><small>${esc(tm)} ${esc(detail)}</small></div>`}).join('')}
function fakeSnapshot(state){const x=stateIndex(state),plate=x>=2?'15C-123.45':'',rfid=x>=2?'RFID-DEMO-001':'',position=x>=5?'ACCEPTED':'—',w=[0,0,0,0,0,300,12000,28420,28460,28460,9400,0][Math.min(x,11)]||0;return {health:{status:'ok',git_sha:'visual-demo'},wf:{state,mode:'NORMAL',transaction:state==='IDLE'?null:{id:'DEMO-20260820-001',station_id:'DEMO-EDGE',position,accepted_weight:x>=8?{weight_kg:28460,stable:true}:null}},scale:{enabled:true,connected:true,last_reading:{weight_kg:w,stable:[0,1,2,3,4,8,9,11].includes(x)}},io:{enabled:true,connected:true,last_input:{entry_present:x>=1&&x<5,front_present:x>=5&&x<10,rear_present:x>=5&&x<10,exit_present:x===10,entry_barrier_open:x>=3&&x<5,exit_barrier_open:x>=9&&x<11,safety_clear:true},applied:{entry_barrier_open:x>=3&&x<5,entry_green:x>=3&&x<5,exit_barrier_open:x>=9&&x<11,exit_green:x>=9&&x<11,buzzer:false}},id:{rfid:{tag:rfid},lpr:{plate}},storage:{integrity:'ok',tickets:x>=8?1:0,pending_sync:x>=8?1:0}}}
function startDemo(startIndex=0,hold=false){live=false;$('demoBanner').classList.add('show');$('demoBtn').classList.add('primary');$('liveBtn').classList.remove('primary');clearInterval(demoTimer);let i=Math.max(0,Math.min(PHASES.length-1,startIndex));data.weights=[];data.events=[];const tick=()=>{const s=PHASES[i];Object.assign(data,fakeSnapshot(s));const w=data.scale.last_reading.weight_kg;data.weights.push({seq:i+1,event:{weight_kg:w,stable:data.scale.last_reading.stable},hash:'demo'});data.events.push({seq:i+1,event:{kind:i===8?'TICKET_COMMITTED':'STATE_TRANSITION',new_state:s,at_utc:new Date().toISOString()},hash:'demo'});render();renderChart();renderTimeline();i++;if(i>=PHASES.length){clearInterval(demoTimer);demoTimer=null}};tick();if(!hold)demoTimer=setInterval(tick,1050)}
function startLive(){live=true;clearInterval(demoTimer);demoTimer=null;$('demoBanner').classList.remove('show');$('liveBtn').classList.add('primary');$('demoBtn').classList.remove('primary');pollFast();pollSlow()}
$('demoBtn').addEventListener('click',()=>startDemo(0,false));$('liveBtn').addEventListener('click',startLive);setInterval(()=>{$('clock').textContent=new Date().toLocaleTimeString([],{hour12:false})},1000);setInterval(pollFast,300);setInterval(pollSlow,1200);
const query=new URLSearchParams(location.search);if(query.get('demo')==='1'){const phase=query.get('phase')||'IDLE';const idx=PHASES.indexOf(phase);startDemo(idx>=0?idx:0,query.get('hold')==='1')}else{$('liveBtn').classList.add('primary');pollFast();pollSlow()}
window.addEventListener('unhandledrejection',e=>{const t=$('toast');t.textContent='UI warning: '+(e.reason?.message||e.reason||'request failed');t.className='toast bad show';setTimeout(()=>t.classList.remove('show'),2600)});
