'use strict';
const PHASES=['IDLE','APPROACH','IDENTIFYING','ENTRY_AUTHORIZED','ENTERING','POSITIONING','READY_TO_WEIGH','WEIGHING','LOCAL_COMMITTED','EXIT_AUTHORIZED','EXITING','COMPLETE'];
const STEP_COPY={IDLE:'Physical lane clear; ready for next pass',APPROACH:'Vehicle detected on ingress side',IDENTIFYING:'RFID + directional C1 LPR identity',ENTRY_AUTHORIZED:'Identity, queue rule and empty-deck proof accepted',ENTERING:'Ingress barrier released',POSITIONING:'Front/rear deck sensors evaluated',READY_TO_WEIGH:'Vehicle positioned; interlocks satisfied',WEIGHING:'Every controller frame audited; stability evaluated',LOCAL_COMMITTED:'This physical pass durably committed',EXIT_AUTHORIZED:'Physical egress authorized after local durability',EXITING:'Vehicle clearing weighbridge',COMPLETE:'Physical pass complete; business cycle may still be queued'};
const POS={IDLE:1,APPROACH:7,IDENTIFYING:13,ENTRY_AUTHORIZED:18,ENTERING:29,POSITIONING:43,READY_TO_WEIGH:48,WEIGHING:50,LOCAL_COMMITTED:53,EXIT_AUTHORIZED:63,EXITING:79,COMPLETE:94,QUEUE_MISMATCH:13,PAIR_INVALID:50,FAULT_LOCKOUT:50};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let live=true,lastLpr='',lastState='',demoTimer=null;
let data={health:null,wf:null,scale:null,io:null,id:null,storage:null,queue:[],weights:[],events:[]};
function fmtN(n){return new Intl.NumberFormat('en-US').format(Number(n||0))}
function short(s,n=8){s=String(s||'');return s?s.slice(0,n):'—'}
function stateIndex(s){const i=PHASES.indexOf(s);return i<0?0:i}
function buildSteps(){$('steps').innerHTML=PHASES.map(p=>`<div class="step" data-phase="${p}"><i class="node"></i><div><strong>${p.replaceAll('_',' ')}</strong><small>${STEP_COPY[p]}</small></div></div>`).join('')}
buildSteps();
async function getJSON(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${url} ${r.status}`);return r.json()}
async function postJSON(url){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'}});if(!r.ok)throw new Error(`${url} ${r.status}: ${await r.text()}`);return r.json()}
async function pollFast(){if(!live)return;const urls=['/healthz','/api/workflow','/api/scale/status','/api/io/status','/api/identity','/api/storage/status','/api/queue'];const res=await Promise.allSettled(urls.map(getJSON));['health','wf','scale','io','id','storage'].forEach((k,i)=>{if(res[i].status==='fulfilled')data[k]=res[i].value});if(res[6].status==='fulfilled')data.queue=res[6].value.items||[];render();renderQueue()}
async function pollSlow(){if(!live)return;const res=await Promise.allSettled([getJSON('/api/audit/weights?limit=120'),getJSON('/api/audit/events?limit=100'),getJSON('/api/audit/weights/verify'),getJSON('/api/audit/events/verify')]);if(res[0].status==='fulfilled')data.weights=res[0].value.records||[];if(res[1].status==='fulfilled')data.events=res[1].value.records||[];$('rawVerify').textContent=res[2].status==='fulfilled'&&res[2].value.verified?'VERIFIED':'—';$('eventVerify').textContent=res[3].status==='fulfilled'&&res[3].value.verified?'VERIFIED':'—';renderChart();renderTimeline();renderMetrics()}
function flash(id){const el=$(id);if(!el)return;el.classList.remove('flash');void el.offsetWidth;el.classList.add('flash')}
function activeCycle(tx){if(!tx?.cycle_id)return null;return (data.queue||[]).find(x=>x.id===tx.cycle_id)||null}
function render(){const h=data.health||{},wf=data.wf||{},sc=data.scale||{},io=data.io||{},identity=data.id||{},st=data.storage||{};const state=wf.state||'IDLE',mode=wf.mode||wf.transaction?.mode||'NORMAL',tx=wf.transaction||{};const direction=tx.direction||'',pass=Number(tx.pass_number||0),cycle=activeCycle(tx);
 $('healthDot').className='dot '+(h.status==='ok'?'ok':'bad');$('healthText').textContent=h.status==='ok'?'EDGE ONLINE':'EDGE OFFLINE';
 const station=tx.station_id||h.station_id||'EDGE-01';$('stationTop').textContent=station;$('stationScene').textContent=station;$('dbTop').textContent=st.integrity==='ok'?'OK':'—';$('syncTop').textContent=st.pending_sync??'—';$('shaMini').textContent=short(h.git_sha||'',10);
 $('stateBadge').textContent=state.replaceAll('_',' ');$('modeBadge').textContent=mode;$('modeBadge').className='modebadge '+(String(mode).includes('DEGRADED')?'degraded':state==='FAULT_LOCKOUT'?'lockout':'');
 const business=tx.business_complete?'COMPLETE':(tx.cycle_status||((data.queue||[]).some(x=>x.status==='CALLED')?'CALLED':(data.queue||[]).length?'QUEUED':'WAITING'));$('businessBadge').textContent=business;$('businessBadge').className='modebadge '+(business==='COMPLETE'?'':business.includes('INVALID')||business.includes('MISMATCH')?'lockout':'degraded');
 $('txShort').textContent=tx.id?`PASS ${pass||'?'} · ${short(tx.id,8)}`:'NO ACTIVE PASS';$('directionText').textContent=direction?direction.replaceAll('_','→'):'—';$('passText').textContent=pass?`#${pass}`:'—';$('cycleText').textContent=tx.cycle_id?short(tx.cycle_id,12):'—';$('cycleStatus').textContent=tx.cycle_status||'—';
 const gross=Number(tx.gross_kg||cycle?.gross_kg||cycle?.first_pass?.weight?.weight_kg||0),tare=Number(tx.tare_kg||0),net=Number(tx.net_kg||0);$('pairText').textContent=gross?`${fmtN(gross)} / ${tare?fmtN(tare):'—'} / ${net?fmtN(net):'—'}`:'—';$('netText').textContent=net?`${fmtN(net)} kg`:'—';
 document.querySelectorAll('.step').forEach(el=>{const p=el.dataset.phase,pi=stateIndex(p),si=stateIndex(state);el.classList.toggle('done',!['FAULT_LOCKOUT','QUEUE_MISMATCH','PAIR_INVALID'].includes(state)&&pi<si);el.classList.toggle('active',p===state);el.classList.toggle('block',['FAULT_LOCKOUT','QUEUE_MISMATCH','PAIR_INVALID'].includes(state)&&p==='WEIGHING')});
 const reading=sc.last_reading||tx.accepted_weight||{},weight=reading.weight_kg??0,stable=!!reading.stable||!!tx.accepted_weight;$('weight').textContent=`${fmtN(weight)} kg`;$('weight').className='weight '+(stable?'stable':'');$('weightState').textContent=sc.connected?(stable?'STABLE · RAW-AUDITED':'LIVE · UNSTABLE'):(tx.accepted_weight?'ACCEPTED PASS WEIGHT':'WAITING FOR LIVE FRAME');$('scaleDeck').classList.toggle('active',state==='WEIGHING'||state==='READY_TO_WEIGH');
 const inp=io.last_input||{},ap=io.applied||{};$('sEntry').classList.toggle('on',!!inp.entry_present);$('sFront').classList.toggle('on',!!inp.front_present);$('sRear').classList.toggle('on',!!inp.rear_present);$('sExit').classList.toggle('on',!!inp.exit_present);$('entryBarrier').classList.toggle('open',!!inp.entry_barrier_open||!!ap.entry_barrier_open);$('exitBarrier').classList.toggle('open',!!inp.exit_barrier_open||!!ap.exit_barrier_open);$('entryLight').classList.toggle('go',!!ap.entry_green);$('exitLight').classList.toggle('go',!!ap.exit_green);
 const rfid=identity.rfid?.tag||tx.rfid?.tag||tx.rfid||'',plate=identity.lpr?.plate||tx.lpr?.plate||tx.plate||'';$('rfidText').textContent=rfid||'—';$('plateText').textContent=plate||'—';$('plateTruck').textContent=plate||'—';$('positionText').textContent=tx.position||'—';$('rfid').classList.toggle('scan',state==='IDENTIFYING'&&!rfid);
 if(state!==lastState){if(state==='IDENTIFYING')flash(direction==='B_TO_A'?'camC1B':'camC1A');if(state==='WEIGHING'||state==='LOCAL_COMMITTED')flash('camC3');lastState=state}else if(plate&&plate!==lastLpr){flash(direction==='B_TO_A'?'camC1B':'camC1A')}lastLpr=plate;
 const base=POS[state]??50,x=direction==='B_TO_A'?100-base:base,flip=direction==='A_TO_B'?-1:1;$('truck').style.transform=`translateX(calc(${x} * (100vw - 610px) / 100)) scaleX(${flip})`;$('plateTruck').style.transform=flip===-1?'scaleX(-1)':'';$('truck').classList.toggle('moving',['APPROACH','ENTERING','EXITING'].includes(state));
 $('sigScale').className='sig '+(sc.connected?'ok':sc.enabled===false?'':'bad');$('devScale').textContent=sc.connected?'CONNECTED · '+(stable?'STABLE':'STREAMING'):(sc.enabled===false?'DISABLED':'DISCONNECTED');$('sigIO').className='sig '+(io.connected?'ok':io.enabled===false?'':'bad');$('devIO').textContent=io.connected?'MODBUS CONNECTED':(io.enabled===false?'DISABLED':'DISCONNECTED');$('sigRFID').className='sig '+(rfid?'ok':'');$('devRFID').textContent=rfid||'WAITING';$('sigLPR').className='sig '+(plate?'ok':'');$('devLPR').textContent=plate?`C1 CAPTURE · ${plate}`:'C1A · C1B · C3 CONFIGURED';renderMetrics();
 document.documentElement.dataset.uiState=state;document.documentElement.dataset.uiWeight=String(weight);document.documentElement.dataset.uiPlate=plate;document.documentElement.dataset.uiMode=live?'live':'demo';document.documentElement.dataset.uiCycle=business;
}
function renderMetrics(){const st=data.storage||{};$('queued').textContent=st.queued_cycles??0;$('called').textContent=st.called_cycles??0;$('completed').textContent=st.completed_cycles??0;$('pending').textContent=st.pending_sync??0}
function renderQueue(){const q=data.queue||[];if(!q.length){$('queueList').innerHTML='<div class="empty">No queued first-pass vehicles</div>';return}$('queueList').innerHTML=q.map(c=>{const gross=c.first_pass?.weight?.weight_kg||c.gross_kg||0,age=c.queued_at?Math.max(0,Math.round((Date.now()-new Date(c.queued_at).getTime())/60000)):0,call=c.status==='QUEUED'&&live?`<button class="btn" style="height:26px;margin-top:5px" data-call="${esc(c.id)}">CALL</button>`:'';return `<div class="event ${c.status==='CALLED'?'ticket':''}"><b>${esc(c.plate)} · ${esc(c.status)}</b><small>${fmtN(gross)} kg gross · ${age} min · ${esc(short(c.id,10))}</small>${call}</div>`}).join('');document.querySelectorAll('[data-call]').forEach(b=>b.onclick=()=>callCycle(b.dataset.call))}
async function callCycle(id){if(!live||!id)return;try{await postJSON(`/api/queue/${encodeURIComponent(id)}/call`);showToast('Cycle CALLED — admit only the matching B→A truck',false);await pollFast()}catch(e){showToast(e.message,true)}}
function showToast(msg,bad){const t=$('toast');t.textContent=msg;t.className='toast '+(bad?'bad ':'')+'show';setTimeout(()=>t.classList.remove('show'),3000)}
function renderChart(){const rec=data.weights||[];if(!rec.length){$('chartLine').setAttribute('d','');$('chartStable').setAttribute('d','');$('chartDot').setAttribute('cx','0');return}const vals=rec.map(r=>({w:Number(r.event?.weight_kg??0),stable:!!r.event?.stable}));const max=Math.max(1000,...vals.map(v=>Math.abs(v.w)))*1.08,min=Math.min(0,...vals.map(v=>v.w)),range=max-min||1;const pts=vals.map((v,i)=>({x:i/(Math.max(1,vals.length-1))*1000,y:108-((v.w-min)/range)*100}));$('chartLine').setAttribute('d',pts.map((p,i)=>(i?'L':'M')+p.x.toFixed(1)+' '+p.y.toFixed(1)).join(' '));let seg='',open=false;pts.forEach((p,i)=>{if(vals[i].stable){seg+=(open?' L':' M')+p.x.toFixed(1)+' '+p.y.toFixed(1);open=true}else open=false});$('chartStable').setAttribute('d',seg);const p=pts[pts.length-1];$('chartDot').setAttribute('cx',p.x);$('chartDot').setAttribute('cy',p.y);$('chartMeta').textContent=`${vals.length} audited frames · peak ${fmtN(Math.max(...vals.map(v=>v.w)))} kg`}
function renderTimeline(){const rows=(data.events||[]).slice(-35).reverse();if(!rows.length){$('timeline').innerHTML='<div class="empty">Waiting for operational audit events…</div>';return}$('timeline').innerHTML=rows.map(r=>{const e=r.event||{},k=e.kind||'EVENT',cl=k.includes('OUTPUT')?'cmd':k.includes('TICKET')?'ticket':k.includes('FAULT')?'fault':'';const detail=e.action||e.reason||e.new_state||e.device||'',tm=e.at_utc?new Date(e.at_utc).toLocaleTimeString([],{hour12:false}):'';return `<div class="event ${cl}"><b>#${r.seq||'?'} ${esc(k)}</b><small>${esc(tm)} ${esc(detail)}</small></div>`}).join('')}
function fakeSnapshot(state,direction='A_TO_B',pass=1,cycleStatus='',businessComplete=false,weightOverride=null){const x=stateIndex(state),plate=x>=2?'15C-123.45':'',rfid=x>=2?'RFID-DEMO-001':'',position=x>=5?'ACCEPTED':'—';let w=weightOverride;if(w===null)w=[0,0,0,0,0,300,12000,28420,28460,28460,9400,0][Math.min(x,11)]||0;const complete=businessComplete?{gross_kg:28460,tare_kg:11820,net_kg:16640,pair_elapsed_seconds:2712}:{gross_kg:pass===2?28460:0};return {health:{status:'ok',git_sha:'visual-demo',two_pass_cycle:true},wf:{state,mode:'NORMAL',transaction:state==='IDLE'?null:{id:`DEMO-PASS-${pass}`,station_id:'DEMO-EDGE',direction,pass_number:pass,cycle_id:'DEMO-CYCLE-001',cycle_status:cycleStatus,business_complete:businessComplete,position,accepted_weight:x>=8?{weight_kg:pass===1?28460:11820,stable:true}:null,...complete}},scale:{enabled:true,connected:true,last_reading:{weight_kg:w,stable:[0,1,2,3,4,8,9,11].includes(x)}},io:{enabled:true,connected:true,last_input:{entry_present:direction==='A_TO_B'&&x>=1&&x<5,exit_present:direction==='B_TO_A'&&x>=1&&x<5,front_present:x>=5&&x<10,rear_present:x>=5&&x<10,entry_barrier_open:direction==='A_TO_B'&&x>=3&&x<5,exit_barrier_open:direction==='B_TO_A'&&x>=3&&x<5,safety_clear:true},applied:{entry_barrier_open:direction==='A_TO_B'&&x>=3&&x<5,entry_green:direction==='A_TO_B'&&x>=3&&x<5,exit_barrier_open:direction==='B_TO_A'&&x>=3&&x<5,exit_green:direction==='B_TO_A'&&x>=3&&x<5,buzzer:false}},id:{rfid:{tag:rfid},lpr:{plate}},storage:{integrity:'ok',queued_cycles:cycleStatus==='QUEUED'?1:0,called_cycles:cycleStatus==='CALLED'?1:0,completed_cycles:businessComplete?1:0,pending_sync:businessComplete?1:0}}}
const DEMO=[];PHASES.forEach(s=>DEMO.push({state:s,dir:'A_TO_B',pass:1,status:['LOCAL_COMMITTED','EXIT_AUTHORIZED','EXITING','COMPLETE'].includes(s)?'QUEUED':'',weight:null}));DEMO.push({state:'IDLE',dir:'A_TO_B',pass:1,status:'QUEUED',queue:true});DEMO.push({state:'IDLE',dir:'B_TO_A',pass:2,status:'CALLED',queue:true});PHASES.forEach(s=>DEMO.push({state:s,dir:'B_TO_A',pass:2,status:['LOCAL_COMMITTED','EXIT_AUTHORIZED','EXITING','COMPLETE'].includes(s)?'COMPLETE':'CALLED',business:s==='LOCAL_COMMITTED'||s==='EXIT_AUTHORIZED'||s==='EXITING'||s==='COMPLETE',weight:s==='WEIGHING'?11810:null}));
function startDemo(startIndex=0,hold=false,singlePhase=null){live=false;$('demoBanner').classList.add('show');$('demoBtn').classList.add('primary');$('liveBtn').classList.remove('primary');clearInterval(demoTimer);let i=startIndex;data.weights=[];data.events=[];const tick=()=>{const item=singlePhase?{state:singlePhase,dir:'A_TO_B',pass:1,status:'',business:false}:DEMO[i];Object.assign(data,fakeSnapshot(item.state,item.dir,item.pass,item.status,item.business,item.weight??null));if(item.queue||item.status==='QUEUED'||item.status==='CALLED')data.queue=[{id:'DEMO-CYCLE-001',plate:'15C-123.45',status:item.status||'QUEUED',queued_at:new Date(Date.now()-22*60000).toISOString(),first_pass:{weight:{weight_kg:28460}}}];else if(item.business)data.queue=[];const w=data.scale.last_reading.weight_kg;data.weights.push({seq:data.weights.length+1,event:{weight_kg:w,stable:data.scale.last_reading.stable},hash:'demo'});data.events.push({seq:data.events.length+1,event:{kind:item.business?'TICKET_COMMITTED':'STATE_TRANSITION',new_state:item.state,at_utc:new Date().toISOString()},hash:'demo'});render();renderQueue();renderChart();renderTimeline();if(singlePhase||hold)return;i++;if(i>=DEMO.length){clearInterval(demoTimer);demoTimer=null}};tick();if(!hold&&!singlePhase)demoTimer=setInterval(tick,850)}
function startLive(){live=true;clearInterval(demoTimer);demoTimer=null;$('demoBanner').classList.remove('show');$('liveBtn').classList.add('primary');$('demoBtn').classList.remove('primary');pollFast();pollSlow()}
$('demoBtn').addEventListener('click',()=>startDemo(0,false));$('liveBtn').addEventListener('click',startLive);setInterval(()=>{$('clock').textContent=new Date().toLocaleTimeString([],{hour12:false})},1000);setInterval(pollFast,300);setInterval(pollSlow,1200);
const query=new URLSearchParams(location.search);const demo=query.get('demo');if(demo){if(demo==='1')startDemo(0,false);else if(PHASES.includes(demo))startDemo(0,true,demo);else startDemo(0,true)}else{$('liveBtn').classList.add('primary');pollFast();pollSlow()}
window.addEventListener('unhandledrejection',e=>showToast('UI warning: '+(e.reason?.message||e.reason||'request failed'),true));
